[package]
name = "pdf"
version = "0.1.4"
edition = "2024"
description = "A PDF viewer module for Lumen"

[dependencies]
models = { workspace = true }
anyhow = { workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
image = { workspace = true }
log = { workspace = true }
lru = "0.16"
smallvec = "1.13"
font-kit = { version = "0.14.3", features = ["source-fontconfig-dlopen"] }
mupdf = "0.7.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
i18n = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
