use gpui::SharedString;
use gpui_component::IconNamed;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IconName {
    File,
    FileSolid,
    Attachment,
    Trash,
    Settings,
    Add,
    Clear,
    Edit,
    Folder,
    Globe,
    Monitor,
    Cloud,
    Download,
    Output,
    Keyboard,
    Puzzle,
    Info,
    FolderSelect,
    AppIcon,
    ArrowUpDown,
    Minimize,
    Maximize,
    Restore,
    Close,
    Copy,
    Check,
    FolderOpen,
    BookOpen,
    Plus,
    Inbox,
    ChevronDown,
    ChevronRight,
    ChevronLeft,
    ChevronUp,
    LoaderCircle,
    CircleX,
    TriangleAlert,
    Undo,
    Bell,
    Star,
    StarSolid,
}

impl IconNamed for IconName {
    fn path(self) -> SharedString {
        match self {
            Self::File => "icons/file.svg".into(),
            Self::FileSolid => "icons/file_solid.svg".into(),
            Self::Attachment => "icons/attachment.svg".into(),
            Self::Trash => "icons/trash.svg".into(),
            Self::Settings => "icons/settings.svg".into(),
            Self::Add => "icons/add.svg".into(),
            Self::Clear => "icons/clear.svg".into(),
            Self::Edit => "icons/edit.svg".into(),
            Self::Folder => "icons/folder_closed.svg".into(),
            Self::Globe => "icons/globe.svg".into(),
            Self::Monitor => "icons/monitor.svg".into(),
            Self::Cloud => "icons/cloud.svg".into(),
            Self::Download => "icons/download.svg".into(),
            Self::Output => "icons/output.svg".into(),
            Self::Keyboard => "icons/keyboard.svg".into(),
            Self::Puzzle => "icons/puzzle.svg".into(),
            Self::Info => "icons/info.svg".into(),
            Self::FolderSelect => "icons/folder_select.svg".into(),
            Self::AppIcon => "icons/app_icon.png".into(),
            Self::ArrowUpDown => "icons/arrow_up_down.svg".into(),
            Self::Minimize => "icons/minimize.svg".into(),
            Self::Maximize => "icons/maximize.svg".into(),
            Self::Restore => "icons/restore.svg".into(),
            Self::Close => "icons/close_small.svg".into(),
            Self::Copy => "icons/copy.svg".into(),
            Self::Check => "icons/check.svg".into(),
            Self::FolderOpen => "icons/folder_open.svg".into(),
            Self::BookOpen => "icons/book_open.svg".into(),
            Self::Plus => "icons/plus.svg".into(),
            Self::Inbox => "icons/inbox.svg".into(),
            Self::ChevronDown => "icons/chevron_down.svg".into(),
            Self::ChevronRight => "icons/chevron_right.svg".into(),
            Self::ChevronLeft => "icons/chevron_left.svg".into(),
            Self::ChevronUp => "icons/chevron_up.svg".into(),
            Self::LoaderCircle => "icons/loader_circle.svg".into(),
            Self::CircleX => "icons/circle_x.svg".into(),
            Self::TriangleAlert => "icons/triangle_alert.svg".into(),
            Self::Undo => "icons/undo.svg".into(),
            Self::Bell => "icons/bell.svg".into(),
            Self::Star => "icons/star.svg".into(),
            Self::StarSolid => "icons/star_solid.svg".into(),
        }
    }
}
