pub(crate) mod chat_session_view;
mod context_menu;
pub(crate) mod edit_chat_dialog;
mod left_sidebar;
mod page;
pub(crate) mod pip;
pub(crate) mod right_sidebar;
mod scrollbar;
pub(crate) mod streaming_bubble;
mod toolbar;
